name: plain_date_time
version: 0.0.0
homepage: https://github.com/JonasWanke/plain_date_time

environment:
  sdk: '>=3.0.0-417.2.beta <4.0.0'

dependencies:
  clock: ^1.1.1
  collection: ^1.15.0
  dartx: ^1.1.0
  fixed: ^2.4.0
  glados: ^1.1.6
  intl: ^0.18.1
  meta: ^1.3.0
  oxidized: ^5.3.0
  time: ^2.1.1

dev_dependencies:
  supernova:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova
      ref: 3276339a5e21ee456160616167b4697209a02cad
  test: ^1.24.2
