name: chrono
version: 0.0.0
homepage: https://github.com/JonasWanke/chrono

environment:
  sdk: '>=3.0.0-417.2.beta <4.0.0'

dependencies:
  clock: ^1.1.1
  collection: ^1.15.0
  dartx: ^1.1.0
  fixed: ^3.0.0
  glados: ^1.1.6
  intl: ^0.18.1
  meta: ^1.3.0
  oxidized: ^6.0.0
  time: ^2.1.1

dev_dependencies:
  supernova:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova
      ref: d66051f0f016cc42c3b5c6f0135a48875df5417e
  test: ^1.24.2

dependency_overrides:
  http: ^1.0.0
