name: cldr
description: Data from Unicode's Common Locale Data Repository (CLDR)
version: 0.0.0
repository: https://github.com/JonasWanke/chrono

environment:
  sdk: ^3.4.0

dependencies:
  code_builder: ^4.10.0
  collection: ^1.18.0
  dart_style: ^2.3.6
  dartx: ^1.2.0
  freezed_annotation: ^2.4.1
  meta: ^1.3.0
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.3
  supernova:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova
      ref: 6da7cfcf12aa2755ed9f7e1a59458c600ef3e1d0
