include: package:supernova_lints/lints.yaml

linter:
  rules:
    # Some “constructors” return a result, but leaving them next to normal
    # constructors makes more sense.
    sort_constructors_first: false
