name: chrono
description: Strongly-typed timestamps, timezone-independent date/time, and durations for Dart
version: 0.1.0
repository: https://github.com/JonasWanke/chrono

environment:
  sdk: ^3.8.0

dependencies:
  clock: ^1.1.1
  deranged: # ^0.0.0
    # path: ../../deranged
    git:
      url: https://github.com/JonasWanke/deranged.git
      ref: e22124cb7687c3189971671e8829d3ba774c6367
  glados: ^1.1.6
  # intl4x: ^0.10.0
  # intl: ^0.19.0
  json_annotation: ^4.8.1
  meta: ^1.3.0

dev_dependencies:
  supernova_lints:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova_lints
      ref: 12c7ad595be5af4f7119c9c7990b8ce48e79905b
