name: chrono
description: Strongly-typed timestamps, timezone-independent date/time, and durations for Dart
version: 0.1.0
repository: https://github.com/JonasWanke/chrono

environment:
  sdk: ^3.6.0

dependencies:
  clock: ^1.1.1
  deranged: # ^0.0.0
    # path: ../../deranged
    git:
      url: https://github.com/JonasWanke/deranged.git
      ref: d3623a08412048eea309e156017944159ef5dfed
  freezed_annotation: ^2.4.1
  glados: ^1.1.6
  # intl4x: ^0.10.0
  # intl: ^0.19.0
  json_annotation: ^4.8.1
  meta: ^1.3.0
  oxidized: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.3
  supernova:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova
      ref: 6da7cfcf12aa2755ed9f7e1a59458c600ef3e1d0
