name: chrono
description: Strongly-typed timestamps, timezone-independent date/time, and durations for Dart
version: 0.1.0
repository: https://github.com/JonasWanke/chrono

environment:
  sdk: ^3.4.0

dependencies:
  cldr:
    path: ../cldr
  clock: ^1.1.1
  dartx: ^1.1.0
  fixed: '>=2.0.0 <5.0.0'
  glados: ^1.1.6
  json_annotation: ^4.8.1
  meta: ^1.3.0
  oxidized: ^6.0.0

dev_dependencies:
  supernova:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova
      ref: 6da7cfcf12aa2755ed9f7e1a59458c600ef3e1d0
