name: chrono_timezone_compiler
version: 0.0.0
homepage: https://github.com/JonasWanke/chrono
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  chrono:
    path: ../chrono
  fixed: '>=2.0.0 <5.0.0'
  meta: ^1.3.0
  oxidized: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.6
  supernova_lints:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova_lints
      ref: 1fa8535952fa7152f2bad30937e6b5bca4129bea

dependency_overrides:
  http: ^1.0.0
